version: "3"
services:
  node:
    image: node:8
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 3000:3000
    command: ['yarn', 'start']

  install:
    image: node:8
    volumes:
      - ./:/app
    working_dir: /app
    command: ['yarn', 'install']